### ISSUE TITLE
Server-Client connection does not work propertly

### ISSUE THREAD

**Issue by brendenbogi** [ImPavloh/DesktopLimboKeys#1]
I tried doing `pip install -r requirements.txt` but it returned an error;

```
~/DesktopLimboKeys$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in /usr/lib64/python3.12/site-packages (from -r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: pygame in /usr/lib64/python3.12/site-packages (from -r requirements.txt (line 2)) (2.5.2)
Collecting pygetwindow (from -r requirements.txt (line 3))
  Using cached PyGetWindow-0.0.9.tar.gz (9.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32
```

I then tried to run the game anyway; the menu launches and there's music, but the keys are stuck on the top left corner.

**Comment by ImPavloh** [comment]
The installation problem is normal because its trying to install a Windows package on a Linux system. Dont worry, you dont need it

Which Linux distribution (and version) are you using?
I just tested everything on a fresh installation of Ubuntu and it works fine for me
Also check your Python version with `python3 --version`

![image](https://github.com/ImPavloh/DesktopLimboKeys/assets/89773173/541cbef1-35d9-4114-8101-1d939f0f15e4)

**Comment by brendenbogi** [comment]
I'm using Fedora 40 Workstation running in Wayland (X11 also didn't work).
Python version is 3.12.3

**Comment by ImPavloh** [comment]
I just tested it on a Fedora 40 Workstation VM running Wayland and also tried with X11 and it works fine
Do you get any specific error messages on the console?
Maybe its a client-server issue and not a graphical one

**Comment by brendenbogi** [comment]
Only this error;

```
<frozen importlib._bootstrap>:488: RuntimeWarning: Your system is avx2 capable but pygame was not built with support for it. The performance of some of your blits could be adversely affected. Consider enabling compile time detection with environment variables like PYGAME_DETECT_AVX2=1 if you are compiling without cross compilation.
```

**Comment by brendenbogi** [comment]
Retried it again and it gave out an extra error;

```
Error: [Errno 98] Address already in use
```

**Comment by brendenbogi** [comment]
Okay so if I kill the python process before launching it works fine, but if i were to relaunch the game right after finishing a previous one it wouldn't launch properly and gave out error 98

**Comment by ImPavloh** [comment]
Yep, I was right. The issue was related to the _server-client connection termination_ rather than a graphical problem.
I have updated the repository with a commit that should resolve this issue.

If you continue to experience the same problem, reopen this issue or feel free to open another one :) 

Closing this now ty!
